db.movieDetails.find({"rated":"PG-13","year":2013})
db.movieDetails.find({"tomato.meter" : 90})
db.movieDetails.find({"actors":"Robert Downey Jr."})
db.movieDetails.find({"actors":"Scarlett Johansson"})
db.movieDetails.find({"actors.0":"Jeff Bridges"})
db.movieDetails.find({},{"title":1, "tomato.meter":1})
db.movieDetails.find({},{"_id":0, "title":1, "tomato.meter":1})
db.movieDetails.find({"actors":["Gordon Auld","Howie Boulware Jr.","Tod Boulware","Chen Drachman"]})
db.movieDetails.find({"rated":"PG-13","year":2013,"awards.wins": 0})
db.movieDetails.find({"awards.oscars.award":"bestPicture"})
db.movieDetails.find({"awards.oscars.award":"bestPicture"})
db.movieDetails.find({"tomato.meter" : {$gt:90}},{"_id":0, "title":1, "tomato.meter":1})
db.movieDetails.find({"countries.1":"Sweden"}).limit(1)
db.movieDetails.find({"rated":{$ne:"UNRATED"}},{"_id":0,"title":1,"rated":1})
db.movieDetails.find({"title":"Turks in Space","tomato.meter":{$ne:70}},{"title":1, "tomato":1})
db.movieDetails.find({"actors":{$in:["Robert Downey Jr.","Jeff Bridges"]}})
db.movieDetails.find({"title":"Turks in Space","tomato.meter":{$exists:false}},{"title":1, "tomato":1})
db.movieDetails.find({"title":"Iron Man 2","tomato.meter":{$exists:true, $gt:70}},{"title":1, "tomato":1})
db.movieDetails.find({"title":"Iron Man 2","year":{$type:"number"}},{"title":1})
db.movieDetails.find({$or: [ {"year":{$gte:2013}} , {"actors":"Robert Downey Jr."} ]}, {"_id":0, "title":1, "year":1, "actors":1, "tomato.meter":1}).pretty()
db.movieDetails.find( {$and: [{$or: [ {"year":{$gte:2013}} , {"actors":"Robert Downey Jr."} ]}, {"tomato.meter":{$gte:75}}]}, {"_id":0, "title":1, "year":1, "actors":1, "tomato.meter":1}).pretty()
db.movieDetails.find({"genres": {$all:["Comedy","Crime"]}}, {"_id":0, "title":1, "genres":1}).pretty()
db.movieDetails.find({"countries": {$size:2}}, {"_id":0, "title":1, "countries":1}).pretty()
db.movieDetails.find({"genres": ["Comedy","Crime"]}, {"_id":0, "title":1, "genres":1}).pretty()
db.movieDetails.find({"genres": ["Comedy","Crime"]}, {"_id":0, "title":1, "genres":1}).count()
db.movieDetails.find({"genres": {$all:["Comedy","Crime"]}}, {"_id":0, "title":1, "genres":1}).pretty()
db.movieDetails.find({"genres": {$all:["Comedy","Crime"]}}, {"_id":0, "title":1, "genres":1}).count()
db.movieDetails.find({"title":"The Martian"}).pretty()
db.movieDetails.updateOne({"title":"The Martian"},{$set:{"actors.0":"Mark Wahlberg"}})
db.movieDetails.updateOne({"title":"The Martian"},{$inc:{"imdb.votes":1},$set:{"actors.0":"Matt Damon","imdb.ratings":8.5}})
db.movieDetails.updateOne({"title":"The Martian"},{$unset:{"imdb.ratings":""}})
db.movieDetails.updateOne({"title":"The Martian"},{$unset:{"reviews":""}})
db.movieDetails.updateOne({"title":"The Martian"},{$push:{"reviews":{$each:[{"rating":2.5,"date":ISODate("2015-10-26T04:00:00Z"),"reviewer":"Matthew Samuel","text":"There have been better movies made about space, and there are elements of the film that are borderline amateur, such as weak dialogue, an uneven tone, and film cliches."}],$position:1}}})
db.movieDetails.updateOne({"title":"The Martian"},{$push:{"reviews":{$each:[{"rating" : 5,"date" : ISODate("2015-12-18T09:00:00Z"),"reviewer" : "Jarrad C","text" : "The Martian Review: There are some movies you know going into them that they're going to be great. The Martian was not only great but exceeded all my expectations as well. A return to form from director Ridley Scott (Alien, Blade Runner) who directed last year's abysmal 'Exodus: Gods and Kings (which I adeptly gave 1/5 because I was happy that it ended), The Martian soars to the heights of a great space epic. In fact the thing that I loved about the Martian more than Alfonso Curon's 'Gravity' and Christopher Nolan's 'Interstellar' is its optimism. Botanist Mark Watney played by an incredible Matt Damon, plays his character to a tee without depressing or alienating viewers. It is through this lens that we see plausible science (well somewhat plausible) succeed and the audience truly root for Mark Watney to be rescued by his Ares III crew creating a palpitating suspense during the rescue launch. That aside the supporting cast is impeccable, literally every single character feels important and is given enough screen-time to shine, from Jessica Chastain's Commander Lewis to Chitwetel Ejiofer's Vincent Kapoor. Also to be highly commended is the diversity of this cast- where every character is simply just equal- just the way it should be in every film."}, {"rating" : 3,"date" : ISODate("2015-12-13T03:00:00Z"),"reviewer" : "hunterjt13", "text" : "An astronaut/botanist is stranded on Mars and must rely upon ingenuity to survive. It's hard to divorce my opinions about this film from my opinions of the book, for after the film I thought that they had adapted the book but left out all the good parts. The cut that bleeds most is the final chapter, which gives the whole story a philosophical significance that is both poignant and naively inspiring. Nevertheless, what remains is a fine tale of how science, wit, perseverance, and intelligence are greater weapons than anything else. Mark Watney's humor survives in the film, even if the film strips him of his vulgarity, all in the service of obtaining a PG-13 rating (really, we must reexamine why one 'fuck' corrupts thirteen- to seventeen-year-olds so much more than ten, twenty, or 100 'fucks'). Mark Watney's intelligence survives the film version, even if the film's story presents him with fewer obstacles to 'science the shit out of,' all in the service of giving director Ridley Scott the opportunity to show beautiful Martian sunsets in the time allowed. That Mark Watney character is quite a survivor. Overall, please watch the film - it's good and it's values are inspiring - but read the book too."}],$slice:5}}})
db.movieDetails.updateMany({$and:[{"imdb.votes":{$lt:10000}},{"year":{$gte:2010,$lte:2013}},{"tomato.consensus":null},{"tomato.consensus":{$exists:true}}]},{$unset:{"imdb.consensus":""}})
db.movieDetails.find({"tomato.consensus":null}).count()
db.movieDetails.find({},{"tomato.consensus":1})
db.movieDetails.updateMany({$and:[{"imdb.votes":{$lt:10000}},{"year":{$gte:2010,$lte:2013}},{"tomato.consensus":null},{"tomato.consensus":{$exists:true}}]},{$unset:{"tomato.consensus":""}})